version: '3.4'


services:
#api Service
  webapplication1:
    image: upd
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - database
    ports:
        - "8000:80"
       


      #database service
  database: 
     image:  mcr.microsoft.com/mssql/server:latest
     #environment for sql
     environment:
       SA_PASSWORD : "Dreamer1@"
       ACCEPT_EULA: "Y"
     ports:
     - "14331:1433"
     depends_on:
      - migrations

  migrations:
     build:
       context: .
       dockerfile: Migrations.DockerFile



      

